### ISSUE TITLE
Dead link for Firefox extension

### ISSUE THREAD

**Issue by zeref-dragneel** [translate-tools/linguist#101]
![ảnh](https://user-images.githubusercontent.com/95934994/167402192-862c163a-a80d-429c-b874-c4edcaf3580a.png)

**Comment by vitonsky** [comment]
Thanks for info. I'm already escalate this issue.

The AMO is disable all versions of extension due to use `eval` function in latest release to implement custom translators defined by users. I've already create discussion with AMO support.

It's very bad attitude to extension developers from Mozilla side. It's looks like interest conflict and unfair competition. Maybe Mozilla support just want to ban Linguist extension because its implement features better than embedded solution for translation. Because Linguist now can embedded Bergamot project and other translators, so users may want to use Linguist instead embedded translator of firefox.

Anyway, you can use Linguist in chrome right now and if firefox will not response and will not enable Linguist back on this week, i will escalate this conflict

**Comment by zeref-dragneel** [comment]
Thank you for the information

**Comment by vitonsky** [comment]
AMO did enable version 4.0.0 back. I hope incidents like this is never be again on AMO side.
Thanks for attention
