### ISSUE TITLE
Google translator return translated text and original both as translation for some cases

### ISSUE THREAD

**Issue by vitonsky** [translate-tools/linguist#378]
Bug occurs with long text

![image](https://github.com/translate-tools/linguist/assets/86191922/1226d13f-ad37-42e2-9231-2316bebe6796)

**Comment by offset-torque** [comment]
Although this is a bug, I noticed that it is very useful for language learning. Normally I translate an english page to the language I am learning and read it comparing with the popup (original English). 

With this bug I can first read the original sentence in English and then in the language I am learning. This speeds up because I don't need to go up and down between page content and popup.

So maybe this can be implemented as an "inline translation" option if you think other language learners would benefit from it too (and if it is not much effort for you). For example in this case translated text may be bold/different color to differentiate and easy skipping.

By the way, many thanks for this cool extension.

**Comment by vitonsky** [comment]
@offset-torque good idea, i will implement it as opt-in feature, thanks for your feedback
