### ISSUE TITLE
AI-generated translation

### ISSUE THREAD

**Issue by DarDreams** [translate-tools/linguist#394]
Would it be feasible to incorporate an AI-generated translation?

**Comment by vitonsky** [comment]
@DarDreams what you mean? Any modern translation like Google or DeepL created by AI.
When you use BergamotTranslator for offline translation, you actually download AI models once. So AI already here

**Comment by DarDreams** [comment]
The standard AI at Google is a whole different league. I mean, utilizing ChatGPT is what I'm talking about.

**Comment by vitonsky** [comment]
> The standard AI at Google is a whole different league. I mean, utilizing ChatGPT is what I'm talking about.

Ok, it is possible, you can implement your [custom translator](https://github.com/translate-tools/linguist/blob/master/docs/CustomTranslator.md) that uses ChatGPT right now.

However i'm not sure you will satisfied by some reasons:
- ChatGPT have request limits, if you will try to translate a whole page, it will generate a lot of requests, so you will wait long and also some requests may be closed by server because reach limits per second limit
- ChatGPT not always do things proper, so it may return you text with not expected format, so you can't parse it back and will generate error in translator
- For me ChatGPT quality decreased for last half year. Now it's not have a quality higher than Google, unlike it has one year ago

But, you can try and give your feedback. If your research will be successful, you can add your translator implementation to a repository https://github.com/translate-tools/linguist-translators where some custom translators placed

**Comment by vitonsky** [comment]
I close the issue due to inactivity, but if you want to add something, you can reopen it
